exclude: ".*deprecated/"

repos:
  - repo: https://github.com/evmckinney9/jupyter-notebook-naming-hook
    rev: v0.1.1
    hooks:
      - id: enforce-notebook-naming

  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.7.2
    hooks:
      - id: conventional-commits

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.9
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: check-added-large-files
      - id: forbid-submodules
      - id: name-tests-test
        args: [--pytest]
      - id: pretty-format-json
        args: [--autofix]
