# replot_exp_demo.py — auto-generated by %%mplfreeze
import os
from pathlib import Path
import numpy as np, matplotlib.pyplot as plt
import lusca

HERE = Path(__file__).parent
NPZ  = HERE / "exp_demo.npz"

def main():
    os.chdir(HERE)
    data = np.load(NPZ)
    x_data = data['x_data']
    gaussian = data['gaussian']
    exp_decay = data['exp_decay']

    # ---- begin captured plotting cell ----
    with plt.style.context("lusca"):
        fig, ax = plt.subplots(figsize=(3.5, 2.6), constrained_layout=True)

        ax.plot(x_data, gaussian, label="Gaussian $e^{-x^2}$")
        ax.plot(x_data, exp_decay, label="Exponential $e^{-|x|}$")
        ax.fill_between(x_data, gaussian, exp_decay, alpha=0.2)

        ax.set_xlabel("X-axis")
        ax.set_ylabel("Function value")
        ax.legend(loc="upper right")
        plt.show()
    # ---- end captured plotting cell ----

if __name__ == "__main__":
    main()
