# replot_trig_demo.py — auto-generated by %%mplfreeze
import os
from pathlib import Path
import numpy as np, matplotlib.pyplot as plt

HERE = Path(__file__).parent
NPZ = HERE / "trig_demo.npz"


def main():
    os.chdir(HERE)
    data = np.load(NPZ)
    x_data = data["x_data"]
    sine = data["sine"]
    cosine = data["cosine"]
    tanh = data["tanh"]

    # ---- begin captured plotting cell ----
    import lusca.render

    with plt.style.context("lusca"):
        fig, axes = plt.subplots(
            1, 2, figsize=(7.0, 2.6), sharey=True, constrained_layout=True
        )

        axes[0].plot(x_data, sine, label="Sine")
        axes[0].plot(x_data, cosine, label="Cosine")
        axes[0].fill_between(x_data, sine - 0.1, sine + 0.1, alpha=0.2)
        axes[0].fill_between(x_data, cosine - 0.1, cosine + 0.1, alpha=0.2)

        axes[1].plot(sine, tanh, label="Tan vs Sine", linestyle="--")
        axes[1].plot(cosine, tanh, label="Tan vs Cosine", linestyle="--")

        axes[0].set_xlabel("X-axis")
        axes[0].set_ylabel("Y-axis")
        axes[1].set_xlabel("X2-axis")
        axes[1].set_ylabel("Y2-axis")

        axes[0].legend(loc="lower center", bbox_to_anchor=(0.5, -0.35), ncol=2)
        axes[1].legend(loc="lower center", bbox_to_anchor=(0.5, -0.35), ncol=2)
        plt.show()
    # ---- end captured plotting cell ----


if __name__ == "__main__":
    main()
