name: CI (release)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  preflight:
    uses: ./.github/workflows/preflight.yml

  build_wheels:
    needs: preflight
    if: needs.preflight.outputs.ok == 'true'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-14
    env:
      # Skip old Pythons / archs; tweak as you like
      CIBW_SKIP: "cp36-* cp37-* cp38-* pp* *-win32 *-musllinux* *_i686"
    steps:
      - uses: actions/checkout@v4

      # Optional: if you need system deps, add them per OS here

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  release:
    needs: [preflight, build_wheels]
    if: needs.preflight.outputs.ok == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (for changelog)
        uses: actions/setup-node@v4

      - name: Generate Changelog
        run: |
          npm install -g conventional-changelog-cli
          conventional-changelog -p conventionalcommits -r 2 | tail -n +3 > CHANGELOG.tmp

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./wheelhouse
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./wheelhouse/**/*.whl
          body_path: CHANGELOG.tmp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
